### ISSUE TITLE
VersionMeta tag used on websites is not an URI

### ISSUE THREAD

**Issue by grv87** [VersionSchema/VersionMeta#8]
http://versionschema.org says:

> The subtitle and browser window/tab title of this page; both contain a URI within curly braces that is a Version Meta tag

If I see it correctly then the VersionMeta tag is `VSchemaInDev.0`.

But it is not a valid URI according to [RFC 3986](https://tools.ietf.org/html/rfc3986#page-16):

> The scheme and path components are required, though the path may be empty (no characters)

**Comment by jwdonahue** [comment]
Thanks, I'll look into it as soon as I have some spare cycles.  I think I am going to have to come up with a different name for it.  The goal is that tooling would know how to look up names that aren't fully qualified URI's.  In fact, I was planning on offering a free service for that purpose, but their would be an extremely limited number of short-names.  SemVer-2.0.0 would of course be one of them.

**Comment by grv87** [comment]
How about registry of version schemas, using [SPDX License List](https://spdx.org/licenses/) as an example?

**Comment by jwdonahue** [comment]
Ya, all we really need is a very simple key value pair service.  Hmmm... I wrote one of those once ;).
